### ISSUE TITLE
Scrollview horizontal not working

### ISSUE THREAD

**Issue by macazaga** [yomybaby/kr.yostudio.drawer#14]
Hi

if i add a scrollview with horizontal layout under a view the app crashes:

[ERROR] :  V8Exception: Exception occurred at ti:/titanium.js:315: Uncaught Error: Attempt to invoke virtual method 'boolean ti.modules.titanium.ui.widget.TiUIScrollView.getScrollingEnabled()' on a null object reference

can you help me?

thanks!

**Comment by yomybaby** [comment]
Can you give more detail?

**Comment by macazaga** [comment]
Sure
i've this view, but crashes because the horizontal scrollview, when i remove that scrollview the app works. Do you know why?

`<Alloy>
    <View id="mapContainer" keepScreenOn="true">
        <View id="locationSearch">
            <Label id="markerLocation1">Your Current Location</Label>
            <Label id="markerLocation2"></Label>
        </View>
    </View>
   <View id="bottomToolsView" layout="vertical">
        <Scrollview  layout="horitzontal">
        <Button id="btnRequestService">Request1</Button>
                <Button id="btnRequestService">Request2</Button>
               <Button id="btnRequestService">Request2</Button>
       </Scrollview>
    </View>
</Alloy>`

**Comment by nuno** [comment]
Hello @macazaga your `<Scrollview layout="horitzontal">` horizontal <- word is bad spelled, "ScrollView" not "Scrollview" could be that?

Should be:  `<ScrollView layout="horizontal">`

**Comment by macazaga** [comment]
Hi @nuno that was a type error when y posted it here but in the code is fine. Still have the problem.

**Comment by yomybaby** [comment]
@macazaga  The code you pasted is the `leftView`(drawer) controller or `centerWindow`?

**Comment by yomybaby** [comment]
Also this controller has two root view.

```
<Alloy>
    <View></View>
    <View></View>
</Alloy>
```

Why don't you wrap like this?

```
<Alloy>
    <View>
        <View></View>
        <View></View>
    </View>
</Alloy>
```

**Comment by macazaga** [comment]
@yomybaby Is the center view. If i wrap it like that will work?

**Comment by yomybaby** [comment]
I'm not sure this can fix your problem.
But under the window(role="centerWindow") must have only one child for changing centerView via `setCenterView` method.
