### ISSUE TITLE
iOS, stuck on splash screen if "run-on-main-thread = true" on tiapp.xml

### ISSUE THREAD

**Issue by nuno** [yomybaby/kr.yostudio.drawer#16]
Hello @yomybaby

 I use this widget in one big app, we need to flag as true on  tiapp.xml 
`<property name="run-on-main-thread" type="bool">true</property>`

But I found today, and after many tests and also after run the kr.yostudio.drawer app example, that indeed stop on splash screen. 

I will try see what is happen in mean time if you can kindly check that too I appreciate.

**P.S If I omit the that flag or set to false, works ok!.**

**Comment by yomybaby** [comment]
Thanks for reporting. I'll try to find a reason.

**Comment by nuno** [comment]
Testing, you the man!
Fixed Here! Thanks @yomybaby!!!!

@yomybaby Can you explain me please why those have to be defered? :)
