### ISSUE TITLE
How do I style the navigation bar?

### ISSUE THREAD

**Issue by SudoPlz** [yomybaby/kr.yostudio.drawer#3]
Hello, I LOVE your widget, thank you for sharing.

I'd like to know how I can style the navigation bar in iOS, let me explain.

I have 2 xml view files:

`index.xml` 

```
<Alloy>
    <Widget id="drawer" class="container" src="kr.yostudio.drawer" onDraweropen="onDrawerOpen" onDrawerclose="onDrawerClose">
        <View class="menuWrap" role="leftView">
            <Require id="menuC" src="menu">
            </Require>
    /View>
        <Window platform="ios" role="centerWindow" id="titleBearer" title="Dashboard"  >
            <LeftNavButton>
                <View>
                    <Button  class="ion-android-menu barItem" onClick="onMenuButtonClick"/>
                </View>
            </LeftNavButton>
            <TitleControl><Label id="barTitleLbl" class="barItem" >Dashboard</Label></TitleControl>
            <RightNavButton>
                  <View>
                    <Button  class="ion-android-settings barItem" onClick="toggleSettings"/>
                </View>
                <!-- <Widget class="barItem barBtn" src="com.rolandschwan.iconlabel" onClick="toggleSettings"/> -->
            </RightNavButton>
        </Window>

    </Widget>

</Alloy>
```

and `announcements.xml`:

```
<Alloy>
    <Window id="announcementsWindow" class="container">
        <LeftNavButton>
            <Widget id="barMenuBtn" class="barItem barBtn" src="com.rolandschwan.iconlabel" onClick="toggleMenu"/>
        </LeftNavButton>
        <TitleControl><Label id="barTitleLbl" class="barItem" >Announcements</Label></TitleControl>
        <RightNavButton>
            <Widget id="barSettingsBtn" class="barItem barBtn" src="com.rolandschwan.iconlabel" onClick="toggleSettings"/>
        </RightNavButton>

        <TitleControl><Label>Announcements</Label></TitleControl>
        <Label id="dashboardLabel">I am announcements!</Label>
    </Window>
</Alloy>
```

I'm able to style `index.xml` bar like so 
<img width="379" alt="screen shot 2015-09-16 at 11 06 33 pm" src="https://cloud.githubusercontent.com/assets/3070948/9916950/af95530c-5cc7-11e5-9e7a-86a92d0322a1.png">

but I'm not able to style `announcement.xml` bar for some strange reason.
<img width="375" alt="screen shot 2015-09-16 at 11 07 56 pm" src="https://cloud.githubusercontent.com/assets/3070948/9916971/e1230342-5cc7-11e5-8d79-c733f17ab815.png">

Notice that eventhough I define `LeftNavButton`, `TitleControl`, and `RightNavButton` in both views, in the `announcements.xml` view ONLY the `RightNavButton` part of the code actually does what its supposed to. **For example, the title SHOULD  be white!**

Any ideas?
Thanks!

**Comment by nuno** [comment]
@SudoPlz

app.tss

```
"Window": {
  backButtonTitle: '',
  navTintColor: '#ffffff'
}
```

**Comment by SudoPlz** [comment]
Thanks for the reply, but nope, it does not work. `backButtonTitle` does change the back button, but the title remains **black**.
I've also tried all the things below:
`app.tss`

```
"Window": {
    tintColor:"white",
    color: 'white', 
    titleAttributes: {
        color: 'white'
    },
    backButtonTitle:'',
    navTintColor: '#ffffff'
}   
```

**Comment by nuno** [comment]
is in titanium apis docs ;) 

```
"Window": {
  backButtonTitle: '',
  navTintColor: '#ffffff',
  tintColor: '#ffffff',
    titleAttributes: {
        color:'#FFFFFF',
        font: {
            fontFamily :"Lato-Regular",
            fontSize:24
            },
   }
}

```

PS: check if you have another style override this values!

**Comment by SudoPlz** [comment]
Nope, doesn't work..! The title of my Window is still black!

**Comment by nuno** [comment]
Works for me!  Try with window id instead, should work, also clean the build of course and play around.

**Comment by SudoPlz** [comment]
Oh my god, nevermind, it was totally my mistake, I was using 2 TitleControls as it shows above in my code.. I've been wasting the past 4 hours trying to fix something that was in front of my face. Look at my code above, I'm using both 

```
<TitleControl><Label id="barTitleLbl" class="barItem" >Announcements</Label></TitleControl>
```

AND

```
<TitleControl><Label>Announcements</Label></TitleControl>
```

, no wonder the title styling have no effect. 
Thats gotta be a sign that I must go to sleep now.
I apologise for wasting your time nuno.. And again, I really thank you for that great widget !

**Comment by nuno** [comment]
np, any time!

**Comment by yomybaby** [comment]
@nuno :+1:
