### ISSUE TITLE
Memory management.

### ISSUE THREAD

**Issue by SudoPlz** [yomybaby/kr.yostudio.drawer#4]
Hello, I'm trying to do some proper memory allocation using your beautiful widget, so I'm implementing a `cleanup()` function that runs on window close like so:

```
$.personWindow.addEventListener('close', function() {
    // let Alloy clean up listeners to global collections for data-binding
    // always call it since it'll just be empty if there are none
    $.destroy();

    // remove all event listeners on the controller
    $.off();
});
```
- The thing is, `'close'` dispatches only when I go back from a newly opened window to the previous window (nav tree level up) and never when I open a new window.  

I believe it should also close the previous window, since we are not using it, or if not the previous one, maybe the one before the previous etc..
- Also `'close'` dispatches ONLY when I open a new window and NEVER when I change my center view.

The thing is, I'm trying to think of a good way to clean stuff up, and I was wondering:
- Is there a way to know how many levels deep inside the nav tree I currently am. Is there any property I can access?
- In a blind shot, is there perhaps any OTHER way I could be managing my memory allocations other than what I'm currently describing? If yes what is that way?

Again thank you for your widget! I'm grateful!

**Comment by yomybaby** [comment]
Thanks for participation. :+1: 

This is not related with my widget. But this is related with window spec.
Window close event only fire on close. only calling close method or press back button(iOS:nav, android:back).
On navWindow and TabGroup works same way. When nav and tab group open a new window, previous window is remained opened(but blur event fired).

If you want the moment loosing focus, use `blur` event. Check this [official docs](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.Window-event-blur) (careful, there is some different depending on OS.

> Is there a way to know how many levels deep inside the nav tree I currently am. Is there any property I can access?

There is no Ti.API to access to that stack(tree) directly. But you can manage stack in JS or use some modules.

> In a blind shot, is there perhaps any OTHER way I could be managing my memory allocations other than what I'm currently describing? If yes what is that way?

Check this out : [link](http://docs.appcelerator.com/platform/latest/#!/guide/Managing_Memory_and_Finding_Leaks)

If I didn't understand that you mentioned, let me know.

**Comment by SudoPlz** [comment]
You are great man, thank you.

After all I wrote my own code to know how many levels deep I am.
About memory, I wrote a cleanup function to run according to the `close` event, and not the blur.

I still use your widget and its exactly what I was looking for, so again, thank you!
