### ISSUE TITLE
Change color from container where the menu  buttons are

### ISSUE THREAD

**Issue by JPDH** [yomybaby/kr.yostudio.drawer#5]
Hi, 

In your widget examples at the index.xml controller you have an Windows that acts like an navigation bar (the one that has title yo.drawer widget). 

How do i change the background color of this window, because it always shows in gray.

![screen shot 2015-11-12 at 3](https://cloud.githubusercontent.com/assets/11877500/11130411/defe39da-8952-11e5-85dc-3d5a46f4cfde.jpg)

**Comment by yomybaby** [comment]
Now, there is only one way.

edit color, line 234 of `widget.js`.

Change background color of bgView :

```
        this._view.bgView = Ti.UI.createView({
            backgroundColor : 'black',
            opacity: 0,
            left:0
        });
```

https://github.com/yomybaby/kr.yostudio.drawer/blob/master/app/widgets/kr.yostudio.drawer/controllers/widget.js#L234

This works on iOS. I don't know how to change that color in android yet.

**Comment by JPDH** [comment]
Thank you so much for your reply.
Sorry man, I don't want to change color of bgView, that's ok.

Now, i need to change color of top bar, (default is gray) 

![foto2](https://cloud.githubusercontent.com/assets/11877500/11329027/77137a06-9163-11e5-8a76-31ddb3503eb5.jpg)

Thank you so much.

**Comment by nuno** [comment]
That is related to titanium api docs, not from this widget :) 

Check for Window and NavigationWindow api.
http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.Window
http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iOS.NavigationWindow

**Comment by yomybaby** [comment]
@nuno :+1:
