### ISSUE TITLE
Scrollview 

### ISSUE THREAD

**Issue by macazaga** [yomybaby/kr.yostudio.drawer#6]
Hi!

When you have a lot of options in the menu in iphone the scroll is not working.

**Comment by nuno** [comment]
Hello, can you please elaborate a little more?

**Comment by yomybaby** [comment]
One of the good ways is giving test code which reproduces your problem.

**Comment by macazaga** [comment]
@nuno and @yomybaby thanks for your help!

Please add more items to the menu, tell me if the screenshots help.
When there are too many options in the menu in iphone the vertical scroll doesnt work but android works.

![screen shot 2016-02-25 at 8 56 40 pm](https://cloud.githubusercontent.com/assets/2780609/13341903/4a528716-dc02-11e5-8c3b-eef94785c4b1.png)

![screen shot 2016-02-25 at 8 53 39 pm](https://cloud.githubusercontent.com/assets/2780609/13341868/e7c2e546-dc01-11e5-99de-88636d31010f.png)

**Comment by yomybaby** [comment]
OK, I'll try to fix. Thanks for reporting.

**Comment by macazaga** [comment]
Thank you! if you need more information please let me know.

**Comment by yomybaby** [comment]
The reason is example menu list vie have a `canScroll : false` in menu.tss.
I removed it. :smile:

**Comment by macazaga** [comment]
great, thank you! :)
