### ISSUE TITLE
Open Child Window

### ISSUE THREAD

**Issue by macazaga** [yomybaby/kr.yostudio.drawer#8]
Hi @yomybaby,

I need to open a child window with the back button as your widget does. I'll try to explain more. If i click an option in the menu a window opens, in that window i have a button to open a new window, how can i add to that window to the navigationwindow in ios and in Android how can i create a modal window with the back button?

Appreciate your help.

**Comment by yomybaby** [comment]
When you set drawer widget to value of `Alloy.Globals`, you can use that any where.
In my example project, add below code to `index.js`

``` js
Alloy.Globals.mainDrawer = $.index;
```

In other controller such as `cry.js` .. you can call

``` js
Alloy.Globals.mainDrawer.openWindow(Ti.UI.createWindow({title : 'new one' }))
```

I hope that this is what you want 😀

**Comment by macazaga** [comment]
yes! thanks a lot as always for your time and help. :smile:
